id: github-integration
displayName: GitHub Integration
description: |
  Seamlessly adopt New Relic Service catalog with the GitHub Integration.
icon: logo.svg
install:
  primary:
    link:
      url: https://www.newrelic.com
keywords:
  - github integration
  - github
  - integration