id: github-integration
displayName: GitHub Integration
description: |
  Seamlessly adopt New Relic Service catalog with the GitHub Integration.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: github_integration
        frameworkConfigId: github_integration
      requiresAccount: false
keywords:
  - github integration
  - github
  - integration