id: github-integration
displayName: GitHub Integration
description: |
  Seamlessly adopt New Relic Service catalog with the GitHub Integration.
icon: logo.png
install:
  primary:
    link:
      url: https://deploy-preview-19384--docs-website-netlify.netlify.app/docs/infrastructure/host-integrations/host-integrations-list/github-integration/
keywords:
  - github integration
  - github
  - integration